title: Zhe Hu
description: My Personal Webpage
author: Zhe Hu
logo: /static/img/my2.png
github: https://github.com/zjuela
about: Mind Builder

baseurl: ""
url: "https://zjuela.github.io/"

disqus_shortname: aboutzhe 
google_analytics: UA-72862926-1

share:
twitter_username: \#
fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
